# Generated by Django 5.1.3 on 2025-01-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billova_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='Europe/Vienna', max_length=50),
        ),
    ]
