# Generated by Django 5.1.3 on 2025-01-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billova_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['invoice_date_time']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='receipt_as_text',
            new_name='invoice_as_text',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='dateTime',
            new_name='invoice_date_time',
        ),
    ]
