# Generated by Django 5.1.3 on 2025-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billova_app', '0002_alter_usersettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
