# Generated by Django 5.1.3 on 2025-01-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billova_app', '0003_remove_category_user_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
