# Generated by Django 5.1.3 on 2025-01-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billova_app', '0004_remove_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expenses',
            field=models.ManyToManyField(related_name='categories', to='billova_app.expense'),
        ),
    ]
