# Generated by Django 5.1.3 on 2025-01-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billova_app', '0005_category_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expenses',
        ),
        migrations.AddField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(related_name='expenses', to='billova_app.category'),
        ),
    ]
